# -*- coding: utf-8 -*-
"""AnaliseComPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNvi993Gmq32oV5mpyWPFu6zntxal8xD
"""

import pandas as pd
import matplotlib.pyplot as plt
#Bibliotecas danda para a execução do DataFrame
#Biblioteca matplotlib para plotar os graficos
data = {
    'Mes': ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio'],
    'Vendas': [20000, 22000, 25000, 18000, 21000],
}
 #Este é o parâmetro que você passa para o construtor do DataFrame.
 #No exemplo, data é um dicionário onde as chaves são os nomes das colunas e os valores são listas que representam os dados nessas colunas.

df = pd.DataFrame(data)

#O método pd.DataFrame(data) é utilizado para criar um objeto DataFrame na biblioteca Pandas.

print(df.head())
print(df.describe())
#Exibe as primeiras linhas do DataFrame (head()) e estatísticas descritivas básicas (describe()) sobre os dados
plt.figure(figsize=(8, 6)) # Define o tamanho da figura do gráfico.
plt.bar(df['Mes'], df['Vendas'], color='blue')#  Cria um gráfico de barras usando os dados do DataFrame df.
#O eixo x são os meses (df['Mes']) e o eixo y são as vendas (df['Vendas']).
plt.title('Vendas Mensais') #Adiciona um título ao gráfico.
plt.xlabel('Mês') # Adiciona um rótulo ao eixo x.
plt.ylabel('Vendas') # Adiciona um rótulo ao eixo y.
plt.show() # Exibe o gráfico.


df['Variação (%)'] = df['Vendas'].pct_change() * 100
print(df)
#Calcula a variação percentual nas vendas, adiciona uma nova coluna chamada 'Variação (%)'
#ao DataFrame e imprime o DataFrame resultante.