ESCREVA UM PROGRAMA EM LINGUAGEM C QUE RECEBA COMO ENTRADA 6 VALORES INTEIROS, GUARDE OS 6 VALORES INTEIROS EM UM VETOR. CRIE UMA FUNÃO QUE:
  CALCULE  TODOS OS VALORES DO VETOR
   SUBTRAIA  TODOS OS VALORES DO VETOR
    MULTIPLIQUE TODOS OS VALORES DO VETOR
